#!/bin/bash

if [ ! -d "/opt/cura" ]
then
  sudo mkdir /opt/cura
fi

wget -O /tmp/cura-5.2.0-linux.zip -- "https://github.com/Ultimaker/Cura/releases/download/5.2.0/Ultimaker-Cura-5.2.0-linux.zip"

unzip /tmp/cura-5.2.0-linux.zip -d /tmp/cura-5.2.0-linux
mv /tmp/cura-5.2.0-linux/*AppImage /opt/cura/cura-5.2.0-linux.AppImage

sudo chmod +x /opt/cura/cura-5.2.0-linux.AppImage

rm -f /tmp/cura-5.2.0-linux.zip
rm -rf /tmp/cura-5.2.0-linux
