#!/bin/bash


wget -O /tmp/ideaIU.tar.gz -q -- "https://download.jetbrains.com/idea/ideaIU-2022.2.1.tar.gz?_gl=1*4z3l4e*_ga*NDg5Nzk5MDg4LjE2NjA0MDUwMzg.*_ga_9J976DJZ68*MTY2MTE1NTkyNy42LjEuMTY2MTE1NTk1OC4wLjAuMA..&_ga=2.49210596.398675521.1661155927-489799088.1660405038"
sudo mkdir /opt/idea
sudo tar -xzf /tmp/ideaIU.tar.gz --strip-components=1 -C /opt/idea
sudo rm -f /tmp/ideaIU.tar.gz
