#!/bin/bash

wget -O /tmp/studio.tar.gz -- https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2021.2.1.16/android-studio-2021.2.1.16-linux.tar.gz

sudo mkdir /opt/android-studio
sudo tar -xzf /tmp/studio.tar.gz --strip-components=1 -C /opt/android-studio
sudo rm -f /tmp/studio.tar.gz
